### ISSUE TITLE
datepicker style broken

### ISSUE THREAD

**Issue by casyalex** [creativetimofficial/ct-vue-material-dashboard-pro#53]
datepicker style broken.

![mdissue](https://user-images.githubusercontent.com/5988630/50555547-10d87a00-0d09-11e9-9e4c-9521a36bb9e8.gif)

didn't add anything special.just use a layout-item to limit the width

``
      <div class="md-layout-item md-medium-size-50 md-xsmall-size-50 md-size-25">
        <md-datepicker v-model="orderDateFrom">
          <label>Ordered Date From</label>
        </md-datepicker>
      </div>
``

**Comment by dragosct10** [comment]
Hi, @casyalex! Thank you for using our products. To fix it please try to add this line of code in your css: 

```css
.md-datepicker-dialog .md-datepicker-body-content {
    height: 236px !important;
}
```

Please let us know if everything it's working fine! 

Regards, 
Dragos
