### ISSUE TITLE
is this an easter egg? an animation about product-cards

### ISSUE THREAD

**Issue by casyalex** [creativetimofficial/ct-vue-material-dashboard-pro#54]
![easteregg](https://user-images.githubusercontent.com/5988630/50871747-9fc74f80-13f7-11e9-81bf-b882953ef6ff.gif)

when you swipe the cards quickly, will trigger this animation. how to remove it..

**Comment by casyalex** [comment]
@dragosct10 i still want to have that 3 buttons to trigger some events...is there any way to just remove this image fall down behavior?

**Comment by dragosct10** [comment]
Oh, now I understand. There is a small issue there because like you see all the animation it's stopped when you put false value and to fix it please go to the src/assets/scss/md/_cards.scss and add the following style code: 

```css
.md-card:hover [data-header-animation="false"] {
     transform: translate3d(0, -50px, 0);
}
```

Regards,
Dragos
