### ISSUE TITLE
Safari search and icon sort problem

### ISSUE THREAD

**Issue by dragosct10** [creativetimofficial/ct-vue-material-dashboard-pro#6]
Hi! To fix the safari problem with icon sort and the search please follow the next steps: 

1. First regard to the search input please go to the `src/assets/scss/md/_inputs.scss` and on line `396`  add the `appearance` with value `none` like this: 

```css
.md-field{

  .md-input,
  .md-textarea{
    height: 36px;
    padding: 7px 0;
    font-size: 14px !important;
    -webkit-text-fill-color: $black-color !important;
    appearance: none;
  }

...

}
```

2. To fix the sort icon problem please go the `src/assets/scss/md/_tables.scss` and on lines `207` and `208` please change the values 44 and right with auto and 0 like this: 

```css
.paginated-table { 
...

.md-table-head.md-sortable .md-table-sortable-icon,
  .md-table-head.md-table-cell-selection+.md-sortable .md-table-sortable-icon{
    left: auto;
    right: 0;
  }
...
}
```

Regards,
Dragos
